services:
  - type: web
    name: hirewise-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
